### ISSUE TITLE
Coaster Sponsor font size and image size reduce

### ISSUE THREAD

**Issue by IndianGuru** [emergingtechs/devopsdays#11]
Gold Sponsors pay Rs 3.50.000 and a Coaster Sponsor pays Rs 36,000 only - as such reduce the size of font and image of Coaster Sponsor as compared to Gold and other sponsors.

**Comment by wallydrag** [comment]
hello @IndianGuru, i have two samples on this, one is with image size reduction and the other one with both the image size and font size reduction. Reducing font size hampered readability, so i am a bit unsure on this. Can you have a look at both and tell me which one is better to go with? cc @SinisterLight . Also i have used a different image for digital ocean, because the one i received in email is pretty small, i hope that's okay. 

<img width="1280" alt="screen shot 2016-07-16 at 9 03 08 am" src="https://cloud.githubusercontent.com/assets/7490092/16892575/c164381c-4b34-11e6-97fc-b89580412548.png">
<img width="1280" alt="screen shot 2016-07-16 at 9 03 34 am" src="https://cloud.githubusercontent.com/assets/7490092/16892576/c23becd0-4b34-11e6-89ea-e1c47544e03d.png">

**Comment by IndianGuru** [comment]
The first image looks good - go for it!

**Comment by IndianGuru** [comment]
Now fixed.
